import s from "./page.module.css";
import Head from "next/head";
import type { FC, ReactNode } from "react";

interface PageProps {
  children: ReactNode;
}

const Page: FC<PageProps> = ({ children }) => {
  return (
    <div className={s.container}>
      <Head>
        <title>SWA + Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>{children}</main>
    </div>
  );
};
export default Page;
