import type {
  GetServerSidePropsContext,
  InferGetServerSidePropsType,
} from "next";
import Head from "next/head";
import useSWR from "swr";

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const data = { time: new Date().toISOString() };
  return {
    props: data,
  };
}

const fetcher = (url: string) => fetch(url).then((res) => res.json());

export default function About({
  time,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const serverData = time;
  const { data } = useSWR("/api/hello", fetcher);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js on Azure with SSR!</a>
        </h1>

        <p>
          The time on the server is <code>{serverData}</code>
        </p>
        <p>
          <pre>{JSON.stringify(data, null, 2)}</pre>
        </p>
      </main>
    </div>
  );
}
