import type {
  GetServerSidePropsContext,
  InferGetServerSidePropsType,
} from "next";
import Head from "next/head";

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const data = { time: new Date().toISOString() };
  return {
    props: data,
  };
}

export default function About({
  time,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const serverData = time;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js on Azure with SSR!</a>
        </h1>

        <p>
          The time on the server is <code>{time}</code>
        </p>
      </main>
    </div>
  );
}
